import 'font-awesome/css/font-awesome.min.css'
import 'bootstrap/dist/css/bootstrap.css'
import './themes/orange/app.css'
import './themes/admin.scss'

export Root from './root'
export Index from './default'
export List from './list'
export Test from './test'
export Signin from './signin'
